use restaurants;
show collections;
db.restaurant.find().pretty();
db.restaurant.find({},{"restaurant_id":1, "name":1, "borough":1, "cuisine":1}).pretty();
db.restaurant.find({},{"restaurant_id":1, "name":1, "borough":1, "cuisine":1, "_id":0}).pretty();
db.restaurant.find({},{"restaurant_id":1, "name":1, "borough":1, "address.zipcode":1, "_id":0}).pretty();
db.restaurant.find({"borough":"Bronx"}).pretty();
db.restaurant.find({"borough":"Bronx"}).limit(5).pretty();
db.restaurant.find({"borough":"Bronx"}).skip(5).limit(5).pretty();
db.restaurant.find({"grades.score": {$gt :90}});
db.restaurant.find({$or: [{"grades.score": {$gt: 80}},{"grades.score": {$lt: 100}}]});
db.restaurant.find({"address.coord": {$lt : -95.754168}});
db.restaurant.find({$and: [{"borough": "Bronx"},{"cuisine": {$ne : "American"}}, {"grades.score":{$gt : 70}}, {"address.coord" : {$lt : -65.754168}}]});
db.restaurant.find({"cuisine" : {$ne : "American"}, "grades.score" : {$gt :70}, "address.coord" : {lt : -65.754168}});
db.restaurant.find({"cuisine" : {$ne : "American"}, "grades.grade" :"A", "borough": {$ne : "Brooklyn"} }).sort({"cuisine" : -1});
db.restaurant.find({"name" : /^Wil/}, {"restaurant_id" : 1, "name" : 1, "borough": 1, "cuisine" : 1});
db.restaurant.find({"name" : /ces$/}, {"restaurant_id" : 1, "name" : 1, "borough" : 1, "cuisine" : 1});
db.restaurant.find({"name" : /Reg/}, {"restaurant_id" : 1, "name" : 1, "borough" : 1, "cuisine" : 1});
db.restaurant.find({"borough" : "Bronx", $or : [{"cuisine" : "American"},{"cuisine" : "Chinese"}]});
db.restaurant.find({"borough": {$in :["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{"restaurant_id": 1, "name": 1, "borough" : 1, "cuisine" : 1});
db.restaurant.find({"borough": {$nin :["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{"restaurant_id": 1, "name": 1, "borough" : 1, "cuisine" : 1});
db.restaurant.find({"grades.score" : {$not : {$gt :10}}}, {"restaurant_id" : 1, "name" : 1, "borough": 1, "cuisine" : 1});
db.restaurant.find({$or : [{"name": /^Wil/}, {$and : [ {"cuisine" : {$nin : ["American", "Chinees"]}}, {"cuisine" : "peix"}]} ]}, {"restaurant_id": 1, "name": 1, "borough" : 1, "cuisine" : 1});
db.restaurant.find({"grades.grade" : "A", "grades.score" : 11, "grades.date" : ISODate("2014-08-11T00:00:00Z")}, {"restaurant_id" : 1, "name" : 1, "grades" : 1});
db.restaurant.find({"grades.1.grade" : "A", "grades.1.score" : 9, "grades.1.date" : ISODate("2014-08-11T00:00:00Z")}, {"restaurant_id" : 1, "name" : 1, "grades" : 1});
db.restaurant.find({"address.coord.1" : {$gt : 42, $lt : 52}}, {"restaurant_id" : 1, "name" : 1, "address" : 1, "coord" : 1});
db.restaurants.find().sort({"name": 1});
db.restaurant.find().sort({"name" : -1});
db.restaurant.find().sort({"cuisine" : 1, "borough" : -1});
db.restaurant.find({"address.street" : {$exists: true}});
db.restaurant.find({"address.coord" : {$type : "double"}});
db.restaurant.find({"grades.score" : {$mod : [7,0]}},{"restaurant_id" :1, "name" : 1, "grade": 1});
db.restaurant.find({"name" : /mon/},{"name":1,"borough":1,"address.coord": 1, "cuisine": 1});
db.restaurant.find({"name": /^Mad/},{"name":1,"borough":1,"address.coord": 1, "cuisine":1});