-- MySQL Script generated by MySQL Workbench
-- Sun May  1 17:17:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`província`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`província` (
  `provincia_id` INT NOT NULL AUTO_INCREMENT,
  `provincia_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localitat` (
  `localitat_id` INT NOT NULL AUTO_INCREMENT,
  `localitat_nom` VARCHAR(20) NOT NULL,
  `província_provincia_id` INT NOT NULL,
  PRIMARY KEY (`localitat_id`, `província_provincia_id`),
  INDEX `fk_localitat_província_idx` (`província_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_localitat_província`
    FOREIGN KEY (`província_provincia_id`)
    REFERENCES `mydb`.`província` (`provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `clients_nom` VARCHAR(12) NOT NULL,
  `clients_cog` VARCHAR(20) NOT NULL,
  `clients_adr` VARCHAR(25) NOT NULL,
  `clients_cp` SMALLINT(5) NOT NULL,
  `clients_tel` INT NOT NULL,
  `localitat_localitat_id` INT NOT NULL,
  PRIMARY KEY (`clients_id`, `localitat_localitat_id`),
  INDEX `fk_clients_localitat1_idx` (`localitat_localitat_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_localitat1`
    FOREIGN KEY (`localitat_localitat_id`)
    REFERENCES `mydb`.`localitat` (`localitat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`botiga` (
  `botiga_id` INT NOT NULL AUTO_INCREMENT,
  `botiga_adre` VARCHAR(25) NOT NULL,
  `botiga_cp` SMALLINT(5) NOT NULL,
  `localitat_localitat_id` INT NOT NULL,
  `localitat_província_provincia_id` INT NOT NULL,
  PRIMARY KEY (`botiga_id`, `localitat_localitat_id`, `localitat_província_provincia_id`),
  INDEX `fk_botiga_localitat1_idx` (`localitat_localitat_id` ASC, `localitat_província_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_botiga_localitat1`
    FOREIGN KEY (`localitat_localitat_id` , `localitat_província_provincia_id`)
    REFERENCES `mydb`.`localitat` (`localitat_id` , `província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `comanda_hora` DATETIME NOT NULL,
  `comanda_tipus` SET('recollir', 'repartiment') NULL,
  `clients_clients_id` INT NOT NULL,
  `botiga_botiga_id` INT NOT NULL,
  PRIMARY KEY (`comanda_id`, `clients_clients_id`, `botiga_botiga_id`),
  INDEX `fk_comanda_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `mydb`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_botiga_id`)
    REFERENCES `mydb`.`botiga` (`botiga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `categories_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `empleats_nom` VARCHAR(12) NOT NULL,
  `empleats_cog` VARCHAR(20) NOT NULL,
  `empleats_nif` VARCHAR(9) NOT NULL,
  `empleats_tel` INT NOT NULL,
  `botiga_botiga_id` INT NOT NULL,
  `repartidor_repartidor_id` INT NOT NULL,
  `cuiner_cuiner_id` INT NOT NULL,
  PRIMARY KEY (`empleats_id`, `botiga_botiga_id`),
  INDEX `fk_empleats_botiga1_idx` (`botiga_botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleats_botiga1`
    FOREIGN KEY (`botiga_botiga_id`)
    REFERENCES `mydb`.`botiga` (`botiga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productes` (
  `productes_id` INT NOT NULL AUTO_INCREMENT,
  `productes_nom` VARCHAR(20) NOT NULL,
  `productes_descr` TEXT NOT NULL,
  `productes_img` VARCHAR(45) NOT NULL,
  `productes_preu` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`productes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalls_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalls_comanda` (
  `quantitat_producte` INT NOT NULL,
  `productes_productes_id` INT NOT NULL,
  `comanda_comanda_id` INT NOT NULL,
  PRIMARY KEY (`productes_productes_id`, `comanda_comanda_id`),
  INDEX `fk_detalls_comanda_comanda1_idx` (`comanda_comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalls_comanda_productes1`
    FOREIGN KEY (`productes_productes_id`)
    REFERENCES `mydb`.`productes` (`productes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalls_comanda_comanda1`
    FOREIGN KEY (`comanda_comanda_id`)
    REFERENCES `mydb`.`comanda` (`comanda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza_cat` (
  `productes_productes_id` INT NOT NULL,
  `categories_categories_id` INT NOT NULL,
  PRIMARY KEY (`productes_productes_id`, `categories_categories_id`),
  INDEX `fk_pizza_cat_categories1_idx` (`categories_categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_cat_productes1`
    FOREIGN KEY (`productes_productes_id`)
    REFERENCES `mydb`.`productes` (`productes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pizza_cat_categories1`
    FOREIGN KEY (`categories_categories_id`)
    REFERENCES `mydb`.`categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deliver` (
  `comanda_comanda_id` INT NOT NULL,
  `empleats_empleats_id` INT NOT NULL,
  `deliver_time` DATETIME NOT NULL,
  PRIMARY KEY (`comanda_comanda_id`, `empleats_empleats_id`),
  INDEX `fk_deliver_empleats1_idx` (`empleats_empleats_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliver_comanda1`
    FOREIGN KEY (`comanda_comanda_id`)
    REFERENCES `mydb`.`comanda` (`comanda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deliver_empleats1`
    FOREIGN KEY (`empleats_empleats_id`)
    REFERENCES `mydb`.`empleats` (`empleats_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`begudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`begudes` (
  `begudes_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`begudes_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`província`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`província` (
  `provincia_id` INT NOT NULL AUTO_INCREMENT,
  `provincia_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localitat` (
  `localitat_id` INT NOT NULL AUTO_INCREMENT,
  `localitat_nom` VARCHAR(20) NOT NULL,
  `província_provincia_id` INT NOT NULL,
  PRIMARY KEY (`localitat_id`, `província_provincia_id`),
  INDEX `fk_localitat_província_idx` (`província_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_localitat_província`
    FOREIGN KEY (`província_provincia_id`)
    REFERENCES `pizzeria`.`província` (`provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `botiga_id` INT NOT NULL AUTO_INCREMENT,
  `botiga_adre` VARCHAR(25) NOT NULL,
  `botiga_cp` SMALLINT NOT NULL,
  `localitat_localitat_id` INT NOT NULL,
  `localitat_província_provincia_id` INT NOT NULL,
  PRIMARY KEY (`botiga_id`, `localitat_localitat_id`, `localitat_província_provincia_id`),
  INDEX `fk_botiga_localitat1_idx` (`localitat_localitat_id` ASC, `localitat_província_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_botiga_localitat1`
    FOREIGN KEY (`localitat_localitat_id` , `localitat_província_provincia_id`)
    REFERENCES `pizzeria`.`localitat` (`localitat_id` , `província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `categories_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `clients_nom` VARCHAR(12) NOT NULL,
  `clients_cog` VARCHAR(20) NOT NULL,
  `clients_adr` VARCHAR(25) NOT NULL,
  `clients_cp` SMALLINT NOT NULL,
  `clients_tel` INT NOT NULL,
  `localitat_localitat_id` INT NOT NULL,
  `localitat_província_provincia_id` INT NOT NULL,
  PRIMARY KEY (`clients_id`, `localitat_localitat_id`, `localitat_província_provincia_id`),
  INDEX `fk_clients_localitat1_idx` (`localitat_localitat_id` ASC, `localitat_província_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_localitat1`
    FOREIGN KEY (`localitat_localitat_id` , `localitat_província_provincia_id`)
    REFERENCES `pizzeria`.`localitat` (`localitat_id` , `província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`hamburgueses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`hamburgueses` (
  `hamburgueses_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`hamburgueses_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizzas` (
  `pizzas_id` INT NOT NULL AUTO_INCREMENT,
  `categories_categories_id` INT NOT NULL,
  PRIMARY KEY (`pizzas_id`, `categories_categories_id`),
  INDEX `fk_pizzas_categories1_idx` (`categories_categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_categories1`
    FOREIGN KEY (`categories_categories_id`)
    REFERENCES `pizzeria`.`categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productes` (
  `productes_id` INT NOT NULL AUTO_INCREMENT,
  `productes_nom` VARCHAR(20) NOT NULL,
  `productes_descr` TEXT NOT NULL,
  `productes_img` VARCHAR(45) NOT NULL,
  `productes_preu` DECIMAL(3,2) NOT NULL,
  `pizzas_pizzas_id` INT NULL DEFAULT NULL,
  `pizzas_categories_categories_id` INT NULL DEFAULT NULL,
  `hamburgueses_hamburgueses_id` INT NULL DEFAULT NULL,
  `begudes_begudes_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`productes_id`),
  INDEX `fk_productes_pizzas1_idx` (`pizzas_pizzas_id` ASC, `pizzas_categories_categories_id` ASC) VISIBLE,
  INDEX `fk_productes_hamburgueses1_idx` (`hamburgueses_hamburgueses_id` ASC) VISIBLE,
  INDEX `fk_productes_begudes1_idx` (`begudes_begudes_id` ASC) VISIBLE,
  CONSTRAINT `fk_productes_begudes1`
    FOREIGN KEY (`begudes_begudes_id`)
    REFERENCES `pizzeria`.`begudes` (`begudes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productes_hamburgueses1`
    FOREIGN KEY (`hamburgueses_hamburgueses_id`)
    REFERENCES `pizzeria`.`hamburgueses` (`hamburgueses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productes_pizzas1`
    FOREIGN KEY (`pizzas_pizzas_id` , `pizzas_categories_categories_id`)
    REFERENCES `pizzeria`.`pizzas` (`pizzas_id` , `categories_categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`repartidor` (
  `repartidor_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`repartidor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `comanda_hora` DATETIME NOT NULL,
  `comanda_tipus` SET('recollir', 'repartiment') NULL DEFAULT NULL,
  `comanda_preu` DECIMAL(4,2) NOT NULL,
  `clients_clients_id` INT NOT NULL,
  `clients_localitat_localitat_id` INT NOT NULL,
  `clients_localitat_província_provincia_id` INT NOT NULL,
  `botiga_botiga_id` INT NOT NULL,
  `botiga_localitat_localitat_id` INT NOT NULL,
  `botiga_localitat_província_provincia_id` INT NOT NULL,
  `repartidor_repartidor_id` INT NULL DEFAULT NULL,
  `productes_productes_id` INT NOT NULL,
  PRIMARY KEY (`comanda_id`, `clients_clients_id`, `clients_localitat_localitat_id`, `clients_localitat_província_provincia_id`, `botiga_botiga_id`, `botiga_localitat_localitat_id`, `botiga_localitat_província_provincia_id`, `productes_productes_id`),
  INDEX `fk_comanda_clients1_idx` (`clients_clients_id` ASC, `clients_localitat_localitat_id` ASC, `clients_localitat_província_provincia_id` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_botiga_id` ASC, `botiga_localitat_localitat_id` ASC, `botiga_localitat_província_provincia_id` ASC) VISIBLE,
  INDEX `fk_comanda_repartidor1_idx` (`repartidor_repartidor_id` ASC) VISIBLE,
  INDEX `fk_comanda_productes1_idx` (`productes_productes_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_botiga_id` , `botiga_localitat_localitat_id` , `botiga_localitat_província_provincia_id`)
    REFERENCES `pizzeria`.`botiga` (`botiga_id` , `localitat_localitat_id` , `localitat_província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_clients1`
    FOREIGN KEY (`clients_clients_id` , `clients_localitat_localitat_id` , `clients_localitat_província_provincia_id`)
    REFERENCES `pizzeria`.`clients` (`clients_id` , `localitat_localitat_id` , `localitat_província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_productes1`
    FOREIGN KEY (`productes_productes_id`)
    REFERENCES `pizzeria`.`productes` (`productes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_repartidor1`
    FOREIGN KEY (`repartidor_repartidor_id`)
    REFERENCES `pizzeria`.`repartidor` (`repartidor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`cuiner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cuiner` (
  `cuiner_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`cuiner_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `empleats_nom` VARCHAR(12) NOT NULL,
  `empleats_cog` VARCHAR(20) NOT NULL,
  `empleats_nif` VARCHAR(9) NOT NULL,
  `empleats_tel` INT NOT NULL,
  `botiga_botiga_id` INT NOT NULL,
  `botiga_localitat_localitat_id` INT NOT NULL,
  `botiga_localitat_província_provincia_id` INT NOT NULL,
  `repartidor_repartidor_id` INT NOT NULL,
  `cuiner_cuiner_id` INT NOT NULL,
  PRIMARY KEY (`empleats_id`, `botiga_botiga_id`, `botiga_localitat_localitat_id`, `botiga_localitat_província_provincia_id`),
  INDEX `fk_empleats_botiga1_idx` (`botiga_botiga_id` ASC, `botiga_localitat_localitat_id` ASC, `botiga_localitat_província_provincia_id` ASC) VISIBLE,
  INDEX `fk_empleats_repartidor1_idx` (`repartidor_repartidor_id` ASC) VISIBLE,
  INDEX `fk_empleats_cuiner1_idx` (`cuiner_cuiner_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleats_botiga1`
    FOREIGN KEY (`botiga_botiga_id` , `botiga_localitat_localitat_id` , `botiga_localitat_província_provincia_id`)
    REFERENCES `pizzeria`.`botiga` (`botiga_id` , `localitat_localitat_id` , `localitat_província_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleats_cuiner1`
    FOREIGN KEY (`cuiner_cuiner_id`)
    REFERENCES `pizzeria`.`cuiner` (`cuiner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleats_repartidor1`
    FOREIGN KEY (`repartidor_repartidor_id`)
    REFERENCES `pizzeria`.`repartidor` (`repartidor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
